# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CD with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: connect seung-server and hermes-server-cd shell script
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SEUNGKI_SERVER_HOST }}
        username: ${{ secrets.SEUNGKI_SERVER_USERNAME }}
        password: ${{ secrets.SEUNGKI_SERVER_PASSWORD }}
        port: ${{ secrets.SEUNGKI_SERVER_PORT }}
        script: |
          cd /usr/it-hermes-project/hermes-cd/
# sudo ./hermes-server-cd.sh(주석처리)
